window.PUBLICATIONS = [
  {
    slug: "bundledslam",
    status: "IEEE IAEAC 2024 · EI",
    title: "BundledSLAM: An Accurate Visual SLAM System Using Multiple Cameras",
    authors: "Han Song, Cong Liu*, Huafeng Dai",
    affiliation: "Peng Cheng Laboratory and collaborators",
    summary: "BundledSLAM studies accurate visual SLAM using multiple cameras, targeting improved robustness and accuracy over single-camera configurations.",
    pdf: "",
    code: "",
    demo: "",
    dataset: "",
    teaser: "assets/images/avatar.png",
    method: "assets/images/avatar.png",
    results: ["assets/images/avatar.png"],
    resourceNote: "The local folder did not contain a public PDF for this paper. Add the final paper PDF and project figures to replace the temporary visuals.",
    citation: "Song, H.; Liu, C.; Dai, H. BundledSLAM: An Accurate Visual SLAM System Using Multiple Cameras. IEEE IAEAC 2024."
  },
  {
    slug: "stereo-vio-init",
    status: "IEEE ACIRS 2024 · EI · Oral",
    title: "Advancements in Translation Accuracy for Stereo Visual-Inertial Initialization",
    authors: "Han Song, Zhongche Qu, Zhi Zhang, Zihan Ye, Cong Liu*",
    affiliation: "Peng Cheng Laboratory and collaborators",
    summary: "This work focuses on translation accuracy in stereo visual-inertial initialization and examines how initialization choices affect downstream localization quality.",
    pdf: "",
    code: "",
    demo: "",
    dataset: "",
    teaser: "assets/images/avatar.png",
    method: "assets/images/avatar.png",
    results: ["assets/images/avatar.png"],
    resourceNote: "The local folder did not contain a public PDF for this paper. Add the final paper PDF and project figures to replace the temporary visuals.",
    citation: "Song, H.; Qu, Z.; Zhang, Z.; Ye, Z.; Liu, C. Advancements in Translation Accuracy for Stereo Visual-Inertial Initialization. IEEE ACIRS 2024."
  },
  {
    slug: "gaussian-slam-depth-priors",
    status: "CEI 2024 · EI",
    title: "Visual SLAM with 3D Gaussian Primitives and Depth Priors Enabling Novel View Synthesis",
    authors: "Zhongche Qu, Zhi Zhang, Cong Liu*, Jianhua Yin",
    affiliation: "Peng Cheng Laboratory and collaborators",
    summary: "This paper combines 3D Gaussian primitives with depth priors to connect visual SLAM and novel view synthesis.",
    pdf: "",
    code: "",
    demo: "",
    dataset: "",
    teaser: "assets/images/avatar.png",
    method: "assets/images/avatar.png",
    results: ["assets/images/avatar.png"],
    resourceNote: "The local folder did not contain a public PDF for this paper. Add the final paper PDF and project figures to replace the temporary visuals.",
    citation: "Qu, Z.; Zhang, Z.; Liu, C.; Yin, J. Visual SLAM with 3D Gaussian Primitives and Depth Priors Enabling Novel View Synthesis. CEI 2024."
  },
  {
    slug: "dvp-mvs",
    status: "AAAI 2025 · CCF-A",
    title: "DVP-MVS: Synergize Depth-Edge and Visibility Prior for Multi-View Stereo",
    authors: "Zhenlong Yuan, Jinguo Luo, Fei Shen, Zhaoxin Li, Cong Liu, Tianlu Mao, Zhaoqi Wang",
    affiliation: "AAAI 2025",
    summary: "DVP-MVS integrates depth-edge and visibility priors for multi-view stereo, improving reconstruction quality through prior-guided matching and geometry reasoning.",
    pdf: "assets/papers/dvp-mvs.pdf",
    code: "",
    demo: "",
    dataset: "",
    teaser: "assets/figures/dvp-mvs/img-049.png",
    method: "assets/figures/dvp-mvs/img-002.png",
    results: [
      "assets/figures/dvp-mvs/img-000.png",
      "assets/figures/dvp-mvs/img-001.png",
      "assets/figures/dvp-mvs/img-003.png"
    ],
    resourceNote: "PDF and figures were extracted from the local AAAI 2025 paper file.",
    citation: "Yuan, Z.; Luo, J.; Shen, F.; Li, Z.; Liu, C.; Mao, T.; Wang, Z. DVP-MVS: Synergize Depth-Edge and Visibility Prior for Multi-View Stereo. AAAI 2025."
  },
  {
    slug: "msp-mvs",
    status: "AAAI 2025 · CCF-A",
    title: "MSP-MVS: Multi-Granularity Segmentation Prior Guided Multi-View Stereo",
    authors: "Zhenlong Yuan, Cong Liu, Fei Shen, Zhaoxin Li, Jinguo Luo, Tianlu Mao, Zhaoqi Wang",
    affiliation: "AAAI 2025",
    summary: "MSP-MVS introduces multi-granularity segmentation priors into multi-view stereo, using semantic and structural cues to guide depth estimation and reconstruction.",
    pdf: "assets/papers/msp-mvs.pdf",
    code: "",
    demo: "",
    dataset: "",
    teaser: "assets/figures/msp-mvs/img-037.png",
    method: "assets/figures/msp-mvs/img-000.png",
    results: [
      "assets/figures/msp-mvs/img-002.png",
      "assets/figures/msp-mvs/img-018.png",
      "assets/figures/msp-mvs/img-028.png"
    ],
    resourceNote: "PDF and figures were extracted from the local AAAI 2025 paper file.",
    citation: "Yuan, Z.; Liu, C.; Shen, F.; Li, Z.; Luo, J.; Mao, T.; Wang, Z. MSP-MVS: Multi-Granularity Segmentation Prior Guided Multi-View Stereo. AAAI 2025."
  },
  {
    slug: "mr-intelliassist",
    status: "HCII 2025 · Accepted",
    title: "MR-IntelliAssist: A World Cognition Agent Enabling Adaptive Human-AI Symbiosis in Industry 4.0",
    authors: "Cong Liu, Zhenlong Yuan, You Wang, Yanhua Yin, Weichao Luo*, Zhenyu He*, Xiaojun Liang*",
    affiliation: "Peng Cheng Laboratory",
    summary: "MR-IntelliAssist proposes a world cognition agent for adaptive human-AI symbiosis in Industry 4.0, combining mixed reality interfaces with reasoning-oriented industrial assistance.",
    pdf: "assets/papers/mr-intelliassist.pdf",
    code: "",
    demo: "",
    dataset: "",
    teaser: "assets/images/mr-intelliassist.jpg",
    method: "assets/images/wca-framework.png",
    results: [
      "assets/images/mr-intelliassist-before-after.png",
      "assets/figures/mr-intelliassist/img-000.png",
      "assets/figures/mr-intelliassist/page-03.jpg"
    ],
    resourceNote: "Figures combine local project images and extracted pages from the HCII paper PDF.",
    citation: "Liu, C.; Yuan, Z.; Wang, Y.; Yin, Y.; Luo, W.; He, Z.; Liang, X. MR-IntelliAssist: A World Cognition Agent Enabling Adaptive Human-AI Symbiosis in Industry 4.0. HCII 2025."
  },
  {
    slug: "plat",
    status: "HCII 2025 · Accepted",
    title: "PLAT: Predictive LLM-Driven Active Teleoperation with Adaptive Vision and Interaction Optimization",
    authors: "Cong Liu, Zhenlong Yuan, You Wang, Yanhua Yin, Weichao Luo*, Zhenyu He*, Xiaojun Liang*",
    affiliation: "Peng Cheng Laboratory",
    summary: "PLAT explores predictive LLM-driven active teleoperation, using adaptive vision and interaction optimization to support remote human-system operation.",
    pdf: "assets/papers/plat.pdf",
    code: "",
    demo: "",
    dataset: "",
    teaser: "assets/figures/plat/img-002.png",
    method: "assets/figures/plat/img-000.png",
    results: [
      "assets/figures/plat/page-2.jpg",
      "assets/figures/plat/page-3.jpg",
      "assets/figures/plat/page-8.jpg"
    ],
    resourceNote: "Figures were extracted from the local HCII paper PDF.",
    citation: "Liu, C.; Yuan, Z.; Wang, Y.; Yin, Y.; Luo, W.; He, Z.; Liang, X. PLAT: Predictive LLM-Driven Active Teleoperation with Adaptive Vision and Interaction Optimization. HCII 2025."
  },
  {
    slug: "operational-twins",
    status: "HCII 2025 · Accepted",
    title: "From Digital Twins to Operational Twins: Enhancing Real-Time Human-System Interaction and Adaptive Decision Support with DeepSeek R1",
    authors: "Cong Liu, Zhenlong Yuan, You Wang, Yanhua Yin, Weichao Luo*, Zhenyu He*, Xiaojun Liang*",
    affiliation: "Peng Cheng Laboratory",
    summary: "This work reframes digital twins as operational twins, emphasizing real-time human-system interaction and adaptive decision support with DeepSeek R1.",
    pdf: "assets/papers/operational-twins.pdf",
    code: "",
    demo: "",
    dataset: "",
    teaser: "assets/figures/operational-twins/img-001.png",
    method: "assets/figures/operational-twins/img-000.png",
    results: [
      "assets/figures/operational-twins/img-003.png",
      "assets/figures/operational-twins/page-02.jpg",
      "assets/figures/operational-twins/page-05.jpg"
    ],
    resourceNote: "Figures were extracted from the local HCII paper PDF.",
    citation: "Liu, C.; Yuan, Z.; Wang, Y.; Yin, Y.; Luo, W.; He, Z.; Liang, X. From Digital Twins to Operational Twins. HCII 2025."
  },
  {
    slug: "ldfe-slam",
    status: "Machines · Published · JCR Q2",
    title: "LDFE-SLAM: Light-Aware Deep Front-End for Robust Visual SLAM under Challenging Illumination",
    authors: "Cong Liu, You Wang, Weichao Luo*, Yanhong Peng",
    affiliation: "Peng Cheng Laboratory",
    summary: "LDFE-SLAM treats low-light degradation as a geometric feature distribution problem. It combines illumination-adaptive enhancement, SuperPoint deep features, and LightGlue matching to stabilize visual SLAM under severe brightness degradation.",
    pdf: "assets/papers/ldfe-slam.pdf",
    code: "",
    demo: "",
    dataset: "",
    teaser: "assets/images/ldfe-lowlight.png",
    method: "assets/figures/ldfe-slam/img-000.png",
    results: [
      "assets/images/ldfe-performance.png",
      "assets/images/ldfe-trajectory.png",
      "assets/figures/ldfe-slam/img-002.png"
    ],
    resourceNote: "Figures combine the local Machines source folder and extracted pages from the paper PDF.",
    citation: "Liu, C.; Wang, Y.; Luo, W.; Peng, Y. LDFE-SLAM: Light-Aware Deep Front-End for Robust Visual SLAM under Challenging Illumination. Machines."
  },
  {
    slug: "mr-multitwin",
    status: "IEEE-CCSSTA 2025 · EI",
    title: "MR-MultiTwin: A Mixed Reality Platform for Multi-User Control of Industrial Digital Twins",
    authors: "Cong Liu, Xiaoning Zhang, Xiaojun Liang, Weichao Luo, Zhenyu He*",
    affiliation: "Peng Cheng Laboratory",
    summary: "MR-MultiTwin is a mixed-reality platform for multi-user control of industrial digital twins, supporting collaborative interaction and real-time industrial scene operation.",
    pdf: "assets/papers/mr-multitwin.pdf",
    code: "",
    demo: "",
    dataset: "",
    teaser: "assets/images/mr-multitwin-demo.jpg",
    method: "assets/figures/mr-multitwin/img-006.png",
    results: [
      "assets/figures/mr-multitwin/img-005.png",
      "assets/figures/mr-multitwin/img-001.png",
      "assets/figures/mr-multitwin/img-002.png"
    ],
    resourceNote: "Figures combine local project images and extracted figures from the IEEE-CCSSTA paper PDF.",
    citation: "Liu, C.; Zhang, X.; Liang, X.; Luo, W.; He, Z. MR-MultiTwin: A Mixed Reality Platform for Multi-User Control of Industrial Digital Twins. IEEE-CCSSTA 2025."
  }
];
